# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnterprisesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
