# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnterprisesApp', '0002_entreprise_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entreprise',
            new_name='Enterprises',
        ),
    ]
