# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnterprisesApp', '0004_remove_enterprises_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprises',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
