# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnterprisesApp', '0005_enterprises_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprises',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
