# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='username',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
