# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EnterprisesApp', '0007_auto_20170802_2042'),
        ('AccountsApp', '0003_auto_20170802_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='enterprise_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EnterprisesApp.Enterprise'),
        ),
    ]
