# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-04 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntroductionApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='UserProfile',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='email',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='password',
            new_name='mobile_number',
        ),
    ]
